name: Emotion Detection CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: 'pip'

      - name: Verify Python Version
        run: python --version

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip

      - name: Install Base Requirements
        run: |
          pip install -r requirements/base.txt

      - name: Install Tracking Requirements
        run: |
          pip install -r requirements/tracking.txt

      - name: Install CI Requirements
        run: |
          pip install -r requirements/ci.txt

      - name: Check Dependency Conflicts
        run: |
          pip check

      - name: Verify Installation
        run: |
          python -c "import numpy, pandas, sklearn, flask, nltk, xgboost, mlflow; print('Dependencies Installed Successfully')"

      - name: Check DVC
        run: |
          dvc version
          dvc doctor
          
      - name: Check Python Syntax
        run: |
          python -m compileall src
      
      - name: Run Unit Tests
        run: |
          python -m pytest tests -v

      - name: Run Flask Tests
        run: |
          python -m pytest tests/test_flask_app.py -v

      - name: Debug Secrets
        env:
          DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          if [ -z "$DAGSHUB_TOKEN" ]; then
            echo "TOKEN NOT FOUND"
            exit 1
          else
            echo "TOKEN FOUND"
          fi

      - name: Debug DagsHub Auth
        env:
          DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_ACTION }}
        run: |
          python -c "import os; print('TOKEN EXISTS:', os.getenv('DAGSHUB_TOKEN') is not None)"
          python -c "import dagshub; print('DagsHub Version:', dagshub.__version__)"

      - name: Run DVC Pipeline
        env:
          DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_ACTION }}
          DAGSHUB_USERNAME: kush2501
        run: |
          echo "Before dvc repro"
          python -c "import os; print('TOKEN EXISTS:', os.getenv('DAGSHUB_TOKEN') is not None)"
          dvc repro